export default [
  {type: 'blockquoteUI'},
  {type: 'textUI'},
  {type: 'textSidebarUI'},
  {type: 'textImageUI'},
  {type: 'imagesUI'},
  // {type: 'featuredCardsUI'},
  {type: 'gridCardUI'},
  // {type: 'listEventsUI'},
  // {type: 'listExhibitionsPastUI'},
  // {type: 'listExhibitionsUI'},
  {type: 'listFeuilletageUI'},
  {type: 'listImageImages'},
  {type: 'listSerieThematiqueUI'},
  {type: 'listConversationUI'},
  {type: 'listUI'},
  {type: 'listsUI'},
  // {type: 'newsCardUI'},
  {type: 'programmeUI'},
  {type: 'ressourcesUI'},
  {type: 'sliderArtistUI'},
  {type: 'sliderCardUI'},
  {type: 'videoUI'},
  {type: 'hrUI'},
  {type: 'formUI'},
]
