export default [
  {type: 'textUI'},
  {type: 'imagesUI'},
  {type: 'videoUI'},
  {type: 'textImageUI'},
  {type: 'textSidebarUI'},
  {type: 'listUI'},
  {type: 'listsUI'},
  {type: 'sliderCardUI'},
  {type: 'gridCardUI'},
  {type: 'programmeUI'},
  {type: 'newsCardUI'},
  {type: 'featuredCardsUI'},
  {type: 'listFeuilletageUI'},
  {type: 'listImageImages'},
  {type: 'listSerieThematiqueUI'},
  {type: 'listExhibitionsUI'},
  {type: 'listExhibitionsPastUI'},
  {type: 'listEventsUI'},
  {type: 'ressourcesUI'},
  {type: 'formUI'},
]
